version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: a2
#      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    restart: unless-stopped
    volumes:
      - db_vol:/var/lib/mysql


  account:
    depends_on:
      - mysqldb
    container_name: account
    image: account-image
    build: ./account
    ports:
      - "8081:8080"
    environment:
      MYSQL_HOST: "mysqldb"
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: a2
    restart: unless-stopped


  person:
    depends_on:
      - mysqldb
    container_name: person
    image: person-image
    build: ./person
    ports:
      - "8082:8080"
    environment:
      MYSQL_HOST: "mysqldb"
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: a2
    restart: unless-stopped

volumes:
  db_vol: