version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.20
    restart: unless-stopped
#    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=a2
    ports:
      - "3307:3306"

#    volumes:
#      - db:/var/lib/mysql

  account_service:
    depends_on:
      - mysqldb
    build: ./account
    restart: on-failure
#    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver"
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/a2?serverTimezone=Australia/Sydney",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.logging.level.org.hibernate.SQL=debug",
        "spring.jpa.show-sql=true"
      }'
#     volumes:
#       - .m2:/root/.m2
#     stdin_open: true
#     tty: true
#
# volumes:
#   db: